spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/product-service
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      password: 0
      database: 0
server:
  port: 8082

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG