spring:
  application:
    name: notification-services
    user-services-url: http://localhost:8080
  datasource:
    url: jdbc:postgresql://localhost:5435/notificationservices
    username: postgres
    password: dontwastetime
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
        "[use_sql_comments]": true
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
mail:
  host: ${MAIL_HOST}
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  debug: true
server:
  port: 8086